# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityzonegoods',
            name='activity_zone',
        ),
        migrations.RemoveField(
            model_name='activityzonegoods',
            name='goods_sku',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cargo_sku',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ActivityZone',
        ),
        migrations.DeleteModel(
            name='ActivityZoneGoods',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
