# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_auto_20180925_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=150, verbose_name='活动专区名称')),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动专区的简介')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('added', models.BooleanField(choices=[(0, '上架'), (1, '下架')], default=0, verbose_name='上否上线')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityZoneGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('activity_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.ActivityZone', verbose_name='活动专区ID')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.SKU', verbose_name='专区商品SKU_ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='轮播活动名字')),
                ('img', models.ImageField(upload_to='static/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('cargo_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.SKU', verbose_name='商品SKU表')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=150, verbose_name='活动名称')),
                ('img', models.ImageField(upload_to='static/%Y%m/%d', verbose_name='活动图片地址')),
                ('url_site', models.CharField(max_length=200, verbose_name='活动的url地址')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
            },
        ),
    ]
