# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(blank=True, choices=[('3', '保密'), ('1', '女'), ('0', '男')], default='0', null=True, verbose_name='性别')),
                ('birthday', models.CharField(blank=True, max_length=20, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=20, null=True, verbose_name='学校')),
                ('place', models.CharField(blank=True, max_length=20, null=True, verbose_name='位置')),
                ('hometown', models.CharField(blank=True, max_length=20, null=True, verbose_name='故乡')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
