# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180922_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[('1', '女'), ('3', '保密'), ('0', '男')], default='0', null=True, verbose_name='性别'),
        ),
    ]
