# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180922_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机格式化错误!')], verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (3, '保密')], default=1, verbose_name='性别'),
        ),
    ]
